// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'astro_user';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String BUBBLE_IMG = 'assets/icons/bubble_img.png';
  static const String VERIFY = 'assets/icons/verify.png';
  static const String SURYAPATH = 'assets/images/SURYAPATH.jpeg';
  static const String APP_ICON = 'assets/images/app_icon.png';
  static const String APP_LOGO = 'assets/images/app_logo.png';
  static const String ASTRO = 'assets/images/astro.jpg';
  static const String BACKGROUND = 'assets/images/background.png';
  static const String BG_JOIN_SESSION_HOME = 'assets/images/bg_join_session_home.jpeg';
  static const String BG_LOGIN = 'assets/images/bg_login.jpeg';
  //static const String BUBBLE_IMG = 'assets/images/bubble_img.png';
  static const String LIVE_SESSION_BG = 'assets/images/live_session_bg.png';
  static const String FIX_JSON = 'assets/translations/fix_json.js';
  static const String FIX_NAV_TRANSLATIONS = 'assets/translations/fix_nav_translations.py';
}
