// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'astro_user';
  static const String PROJECT_VERSION = '1.0.0+1';
  static String BUBBLE_IMG = 'assets/icons/bubble_img.png';
  static String BUBBLE_IMG_PNG = 'assets/images/bubble_img.png';
  static const String LIVE_SESSION_BG = 'assets/images/live_session_bg.png';
}
