// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa8mEKKiAPYXfMqUZlhbj43yTf0Zb68gI',
    appId: '1:397276146259:web:dfd5b81b2ec87f1c6c34a6',
    messagingSenderId: '397276146259',
    projectId: 'suryapath-kundli',
    authDomain: 'suryapath-kundli.firebaseapp.com',
    databaseURL: 'https://suryapath-kundli-default-rtdb.firebaseio.com',
    storageBucket: 'suryapath-kundli.firebasestorage.app',
    measurementId: 'G-J8QRX3VXBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY6n5avyx8Eg0QRNjQljmCZcaj3UmuVNs',
    appId: '1:397276146259:android:c229db75ff2980046c34a6',
    messagingSenderId: '397276146259',
    projectId: 'suryapath-kundli',
    databaseURL: 'https://suryapath-kundli-default-rtdb.firebaseio.com',
    storageBucket: 'suryapath-kundli.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCZno6COm-LSoW-juWBwtqKpJrrq5Mz9c',
    appId: '1:397276146259:ios:8f937f22fb6877646c34a6',
    messagingSenderId: '397276146259',
    projectId: 'suryapath-kundli',
    databaseURL: 'https://suryapath-kundli-default-rtdb.firebaseio.com',
    storageBucket: 'suryapath-kundli.firebasestorage.app',
    iosClientId: '397276146259-5j9m3i38i2vh2scq4g16nmde1mjq64g4.apps.googleusercontent.com',
    iosBundleId: 'com.suryapath.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCZno6COm-LSoW-juWBwtqKpJrrq5Mz9c',
    appId: '1:397276146259:ios:9b92ba7cf584e0056c34a6',
    messagingSenderId: '397276146259',
    projectId: 'suryapath-kundli',
    databaseURL: 'https://suryapath-kundli-default-rtdb.firebaseio.com',
    storageBucket: 'suryapath-kundli.firebasestorage.app',
    iosClientId: '397276146259-14pivjf70p3gmgh3h71t00grrdqrpk7e.apps.googleusercontent.com',
    iosBundleId: 'hash.code.file.fileStracture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa8mEKKiAPYXfMqUZlhbj43yTf0Zb68gI',
    appId: '1:397276146259:web:d562823657043c7c6c34a6',
    messagingSenderId: '397276146259',
    projectId: 'suryapath-kundli',
    authDomain: 'suryapath-kundli.firebaseapp.com',
    databaseURL: 'https://suryapath-kundli-default-rtdb.firebaseio.com',
    storageBucket: 'suryapath-kundli.firebasestorage.app',
    measurementId: 'G-BB9TQR029F',
  );
}
